1
https://raw.githubusercontent.com/priyanksondagar/Food-Ordering-System/master/FoodOrder.java

package food;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.Random;
import static javafx.scene.input.KeyCode.R;
import javax.swing.JTextField;
import javax.swing.JFrame;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author i
 */
public class FoodOrder extends javax.swing.JFrame {
    
    double SmallPizza=149.00;
    double MediumPizza=299.00;
    double LargePizza=499.00;
    double CocaCola=40.00;
    double ThumsUp=40.00;
    double Sprite=40.00;
    
    /**
     * Creates new form FoodOrder
     */
    public FoodOrder() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jchkboxSpizza = new javax.swing.JCheckBox();
        jchkboxMpizza = new javax.swing.JCheckBox();
        jchkboxLpizza = new javax.swing.JCheckBox();
        jtxtfieldMeal = new javax.swing.JTextField();
        jtxtfieldSmall = new javax.swing.JTextField();
        jtxtfieldMedium = new javax.swing.JTextField();
        jtxtfieldLarge = new javax.swing.JTextField();
        jtxtfieldSmallP = new javax.swing.JTextField();
        jtxtfieldMediumP = new javax.swing.JTextField();
        jtxtfieldLargeP = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jtxtfieldDrink = new javax.swing.JTextField();
        jchkboxCoca = new javax.swing.JCheckBox();
        jchkboxThums = new javax.swing.JCheckBox();
        jchkboxSprite = new javax.swing.JCheckBox();
        jtxtfieldCoca = new javax.swing.JTextField();
        jtxtfieldSprite = new javax.swing.JTextField();
        jtxtfieldThums = new javax.swing.JTextField();
        jtxtfieldCocaP = new javax.swing.JTextField();
        jtxtfieldThumsP = new javax.swing.JTextField();
        jtxtfieldSpriteP = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jbtnTotal = new javax.swing.JButton();
        jbtnOrder = new javax.swing.JButton();
        jbtnReceipt = new javax.swing.JButton();
        jbtnReset = new javax.swing.JButton();
        jbtnExit = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jtxtfieldSub = new javax.swing.JTextField();
        jlableSub = new javax.swing.JLabel();
        jlableSub1 = new javax.swing.JLabel();
        jlableSub2 = new javax.swing.JLabel();
        jtxtfieldTax = new javax.swing.JTextField();
        jtxtfieldTotal = new javax.swing.JTextField();
        jtxtfieldStatus = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtxtfieldReceipt = new javax.swing.JTextArea();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Order Your Food");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jchkboxSpizza.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jchkboxSpizza.setText("Small Pizaa");
        jchkboxSpizza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkboxSpizzaActionPerformed(evt);
            }
        });

        jchkboxMpizza.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jchkboxMpizza.setText("Medium Pizza");
        jchkboxMpizza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkboxMpizzaActionPerformed(evt);
            }
        });

        jchkboxLpizza.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jchkboxLpizza.setText("Large Pizza");
        jchkboxLpizza.setToolTipText("");

        jtxtfieldMeal.setEditable(false);
        jtxtfieldMeal.setBackground(new java.awt.Color(255, 255, 102));
        jtxtfieldMeal.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        jtxtfieldMeal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtfieldMeal.setText("Meal Section");
        jtxtfieldMeal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtfieldMealActionPerformed(evt);
            }
        });

        jtxtfieldSmall.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtfieldSmall.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtfieldSmall.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtfieldSmallFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtxtfieldSmallFocusLost(evt);
            }
        });
        jtxtfieldSmall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtfieldSmallActionPerformed(evt);
            }
        });
        jtxtfieldSmall.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtfieldSmallKeyPressed(evt);
            }
        });

        jtxtfieldMedium.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtfieldMedium.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtfieldMedium.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtfieldMediumFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtxtfieldMediumFocusLost(evt);
            }
        });
        jtxtfieldMedium.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtfieldMediumActionPerformed(evt);
            }
        });
        jtxtfieldMedium.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtfieldMediumKeyPressed(evt);
            }
        });

        jtxtfieldLarge.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtfieldLarge.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtfieldLarge.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtfieldLargeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtxtfieldLargeFocusLost(evt);
            }
        });
        jtxtfieldLarge.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtfieldLargeKeyPressed(evt);
            }
        });

        jtxtfieldSmallP.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtfieldSmallP.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtfieldSmallP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtfieldSmallPActionPerformed(evt);
            }
        });

        jtxtfieldMediumP.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtfieldMediumP.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtfieldMediumP.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtxtfieldMediumPFocusLost(evt);
            }
        });
        jtxtfieldMediumP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtfieldMediumPActionPerformed(evt);
            }
        });

        jtxtfieldLargeP.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtfieldLargeP.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtfieldLargeP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtfieldLargePActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Quantity");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Price");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jchkboxLpizza, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtxtfieldLarge, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jtxtfieldLargeP, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jchkboxMpizza, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)
                                .addComponent(jtxtfieldMedium, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtxtfieldMediumP, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jchkboxSpizza, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtxtfieldSmall, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtxtfieldSmallP, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jtxtfieldMeal, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(56, 56, 56)
                .addComponent(jLabel2)
                .addGap(45, 45, 45))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtxtfieldMeal, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jchkboxSpizza)
                    .addComponent(jtxtfieldSmall, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtfieldSmallP, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jchkboxMpizza)
                    .addComponent(jtxtfieldMedium, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtfieldMediumP, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jchkboxLpizza)
                    .addComponent(jtxtfieldLarge, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtfieldLargeP, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(86, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jtxtfieldDrink.setEditable(false);
        jtxtfieldDrink.setBackground(new java.awt.Color(255, 255, 102));
        jtxtfieldDrink.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        jtxtfieldDrink.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtfieldDrink.setText("Drink Section");
        jtxtfieldDrink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtfieldDrinkActionPerformed(evt);
            }
        });

        jchkboxCoca.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jchkboxCoca.setText("Coca Cola");
        jchkboxCoca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkboxCocaActionPerformed(evt);
            }
        });

        jchkboxThums.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jchkboxThums.setText("Thums Up");
        jchkboxThums.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkboxThumsActionPerformed(evt);
            }
        });

        jchkboxSprite.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jchkboxSprite.setText("Sprite");
        jchkboxSprite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkboxSpriteActionPerformed(evt);
            }
        });

        jtxtfieldCoca.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtfieldCoca.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtfieldCoca.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtfieldCocaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtxtfieldCocaFocusLost(evt);
            }
        });
        jtxtfieldCoca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtfieldCocaActionPerformed(evt);
            }
        });
        jtxtfieldCoca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtfieldCocaKeyPressed(evt);
            }
        });

        jtxtfieldSprite.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtfieldSprite.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtfieldSprite.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtfieldSpriteFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtxtfieldSpriteFocusLost(evt);
            }
        });
        jtxtfieldSprite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtfieldSpriteActionPerformed(evt);
            }
        });
        jtxtfieldSprite.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtfieldSpriteKeyPressed(evt);
            }
        });

        jtxtfieldThums.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtfieldThums.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtfieldThums.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtfieldThumsFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtxtfieldThumsFocusLost(evt);
            }
        });
        jtxtfieldThums.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtfieldThumsActionPerformed(evt);
            }
        });
        jtxtfieldThums.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtfieldThumsKeyPressed(evt);
            }
        });

        jtxtfieldCocaP.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtfieldCocaP.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtfieldCocaP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtfieldCocaPActionPerformed(evt);
            }
        });

        jtxtfieldThumsP.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtfieldThumsP.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtfieldThumsP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtfieldThumsPActionPerformed(evt);
            }
        });

        jtxtfieldSpriteP.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtfieldSpriteP.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtfieldSpriteP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtfieldSpritePActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Quantity");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Price");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jchkboxThums, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jchkboxSprite, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jtxtfieldSprite, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtxtfieldSpriteP, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jtxtfieldThums, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtxtfieldThumsP, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jchkboxCoca)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtxtfieldCoca, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtfieldCocaP, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(68, 68, 68))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(61, 61, 61)
                .addComponent(jLabel4)
                .addGap(101, 101, 101))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jtxtfieldDrink, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtxtfieldDrink, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jchkboxCoca)
                    .addComponent(jtxtfieldCoca, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtfieldCocaP, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jchkboxThums)
                    .addComponent(jtxtfieldThums, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtfieldThumsP, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtfieldSprite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtfieldSpriteP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jchkboxSprite))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jbtnTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnTotal.setText("Total");
        jbtnTotal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnTotalMouseClicked(evt);
            }
        });
        jbtnTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnTotalActionPerformed(evt);
            }
        });

        jbtnOrder.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnOrder.setText("Order");
        jbtnOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnOrderMouseClicked(evt);
            }
        });
        jbtnOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnOrderActionPerformed(evt);
            }
        });

        jbtnReceipt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnReceipt.setText("Receipt");
        jbtnReceipt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnReceiptMouseClicked(evt);
            }
        });

        jbtnReset.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnReset.setText("Reset");
        jbtnReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnResetMouseClicked(evt);
            }
        });
        jbtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResetActionPerformed(evt);
            }
        });

        jbtnExit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnExit.setText("Exit");
        jbtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jbtnTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addComponent(jbtnReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(jbtnOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addComponent(jbtnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addComponent(jbtnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jtxtfieldSub.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtfieldSub.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtfieldSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtfieldSubActionPerformed(evt);
            }
        });

        jlableSub.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlableSub.setText("Sub Total :");

        jlableSub1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlableSub1.setText("TAX :");

        jlableSub2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlableSub2.setText("Total :");

        jtxtfieldTax.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtfieldTax.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtfieldTax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtfieldTaxActionPerformed(evt);
            }
        });

        jtxtfieldTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtfieldTotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtfieldTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtfieldTotalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlableSub)
                    .addComponent(jlableSub1)
                    .addComponent(jlableSub2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtxtfieldTax, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                    .addComponent(jtxtfieldSub)
                    .addComponent(jtxtfieldTotal))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlableSub, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtfieldSub, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtfieldTax, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlableSub1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlableSub2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtfieldTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jtxtfieldStatus.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jtxtfieldStatus.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtfieldStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtfieldStatusActionPerformed(evt);
            }
        });

        jtxtfieldReceipt.setEditable(false);
        jtxtfieldReceipt.setColumns(15);
        jtxtfieldReceipt.setRows(5);
        jScrollPane2.setViewportView(jtxtfieldReceipt);

        jTextField1.setBackground(new java.awt.Color(255, 255, 102));
        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("Price List");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(11);
        jTextArea1.setFont(new java.awt.Font("DejaVu Serif", 1, 16)); // NOI18N
        jTextArea1.setRows(20);
        jTextArea1.setText("\n\n\n   Product             Rs.\n\nSmall Pizza      149.00\n\nMedium Pizza   299.00\n\nLarge Pizza      499.00\n\nCoca Cola        40.00\n\nThums Up        40.00\n\nSprite              40.00");
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)))
                    .addComponent(jtxtfieldStatus))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtxtfieldStatus))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnTotalActionPerformed

    private void jchkboxMpizzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkboxMpizzaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jchkboxMpizzaActionPerformed

    private void jchkboxSpizzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkboxSpizzaActionPerformed

    }//GEN-LAST:event_jchkboxSpizzaActionPerformed

    private void jchkboxCocaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkboxCocaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jchkboxCocaActionPerformed

    private void jchkboxThumsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkboxThumsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jchkboxThumsActionPerformed

    private void jchkboxSpriteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkboxSpriteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jchkboxSpriteActionPerformed

    private void jtxtfieldDrinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtfieldDrinkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtfieldDrinkActionPerformed

    private void jtxtfieldSubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtfieldSubActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtfieldSubActionPerformed

    private void jtxtfieldTaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtfieldTaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtfieldTaxActionPerformed

    private void jtxtfieldTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtfieldTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtfieldTotalActionPerformed

    private void jtxtfieldThumsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtfieldThumsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtfieldThumsActionPerformed

    private void jbtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jbtnExitActionPerformed

    private void jbtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnResetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnResetActionPerformed

    private void jbtnResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnResetMouseClicked
    jtxtfieldTotal.setText(null);
     jtxtfieldCoca.setText(null);
     jtxtfieldLarge.setText(null);
     jtxtfieldMedium.setText(null);
     jtxtfieldSmall.setText(null);
     jtxtfieldSprite.setText(null);
     jtxtfieldSub.setText(null);
     jtxtfieldTax.setText(null);
     jtxtfieldThums.setText(null);
     jtxtfieldSmallP.setText(null);
     jtxtfieldMediumP.setText(null);
     jtxtfieldLargeP.setText(null);
     jtxtfieldCocaP.setText(null);
     jtxtfieldThumsP.setText(null);
     jtxtfieldSpriteP.setText(null);
    jchkboxSpizza.setSelected(false);
    jchkboxMpizza.setSelected(false);
    jchkboxLpizza.setSelected(false);
    jchkboxCoca.setSelected(false);
    jchkboxThums.setSelected(false);      
    jchkboxSprite.setSelected(false);
                                   
                                   
    }//GEN-LAST:event_jbtnResetMouseClicked

    private void jtxtfieldCocaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtfieldCocaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtfieldCocaActionPerformed

    private void jtxtfieldCocaPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtfieldCocaPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtfieldCocaPActionPerformed

    private void jtxtfieldThumsPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtfieldThumsPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtfieldThumsPActionPerformed

    private void jtxtfieldSpritePActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtfieldSpritePActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtfieldSpritePActionPerformed

    private void jtxtfieldSmallPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtfieldSmallPActionPerformed
        String EnterNumber=jtxtfieldSmall.getText();
        double quantity=Double.parseDouble(EnterNumber);
        double price=quantity*SmallPizza;
        String Price=String.format("%.2f", price);
        jtxtfieldSmallP.setText(Price);
    }//GEN-LAST:event_jtxtfieldSmallPActionPerformed

    private void jtxtfieldMediumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtfieldMediumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtfieldMediumActionPerformed

    private void jtxtfieldLargePActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtfieldLargePActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtfieldLargePActionPerformed

    private void jtxtfieldSpriteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtfieldSpriteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtfieldSpriteActionPerformed

    private void jbtnOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnOrderActionPerformed
        
    }//GEN-LAST:event_jbtnOrderActionPerformed

    private void jtxtfieldMealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtfieldMealActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtfieldMealActionPerformed

    private void jbtnOrderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnOrderMouseClicked
        
        jtxtfieldStatus.setText("Order received !!!");
    }//GEN-LAST:event_jbtnOrderMouseClicked

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jtxtfieldStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtfieldStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtfieldStatusActionPerformed

    private void jtxtfieldSmallKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtfieldSmallKeyPressed
        String EnterNumber=jtxtfieldSmall.getText();
        double quantity=Double.parseDouble(EnterNumber);
        double price=quantity*SmallPizza;
        String Price=String.format("%.2f", price);
        jtxtfieldSmallP.setText(Price);
        jchkboxSpizza.setSelected(true);
    }//GEN-LAST:event_jtxtfieldSmallKeyPressed

    private void jtxtfieldSmallFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtfieldSmallFocusLost
        String EnterNumber=jtxtfieldSmall.getText();
        double quantity=Double.parseDouble(EnterNumber);
        double price=quantity*SmallPizza;
        String Price=String.format("%.2f", price);
        jtxtfieldSmallP.setText(Price);
        if(quantity>0)
        {jchkboxSpizza.setSelected(true);}
    }//GEN-LAST:event_jtxtfieldSmallFocusLost

    private void jtxtfieldMediumPFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtfieldMediumPFocusLost
        
    }//GEN-LAST:event_jtxtfieldMediumPFocusLost

    private void jtxtfieldMediumPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtfieldMediumPActionPerformed
        String EnterNumber=jtxtfieldMedium.getText();
        double quantity=Double.parseDouble(EnterNumber);
        double price=quantity*MediumPizza;
        String Price=String.format("%.2f", price);
        jtxtfieldMediumP.setText(Price);
    }//GEN-LAST:event_jtxtfieldMediumPActionPerformed

    private void jtxtfieldMediumFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtfieldMediumFocusLost
        String EnterNumber=jtxtfieldMedium.getText();
        double quantity=Double.parseDouble(EnterNumber);
        double price=quantity*MediumPizza;
        String Price=String.format("%.2f", price);
        jtxtfieldMediumP.setText(Price);
        if(quantity>0)
        {jchkboxMpizza.setSelected(true);}
    }//GEN-LAST:event_jtxtfieldMediumFocusLost

    private void jtxtfieldLargeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtfieldLargeFocusLost
        String EnterNumber=jtxtfieldLarge.getText();
        double quantity=Double.parseDouble(EnterNumber);
        double price=quantity*LargePizza;
        String Price=String.format("%.2f", price);
        jtxtfieldLargeP.setText(Price);
        if(quantity>0)
        {jchkboxLpizza.setSelected(true);}
    }//GEN-LAST:event_jtxtfieldLargeFocusLost

    private void jtxtfieldCocaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtfieldCocaFocusLost
        String EnterNumber=jtxtfieldCoca.getText();
        double quantity=Double.parseDouble(EnterNumber);
        double price=quantity*CocaCola;
        String Price=String.format("%.2f", price);
        jtxtfieldCocaP.setText(Price);
        if(quantity>0)
        {jchkboxCoca.setSelected(true);}
    }//GEN-LAST:event_jtxtfieldCocaFocusLost

    private void jtxtfieldThumsFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtfieldThumsFocusLost
        String EnterNumber=jtxtfieldThums.getText();
        double quantity=Double.parseDouble(EnterNumber);
        double price=quantity*ThumsUp;
        String Price=String.format("%.2f", price);
        jtxtfieldThumsP.setText(Price);
        if(quantity>0)
        {jchkboxThums.setSelected(true);}
    }//GEN-LAST:event_jtxtfieldThumsFocusLost

    private void jtxtfieldSpriteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtfieldSpriteFocusLost
        String EnterNumber=jtxtfieldSprite.getText();
        double quantity=Double.parseDouble(EnterNumber);
        double price=quantity*Sprite;
        String Price=String.format("%.2f", price);
        jtxtfieldSpriteP.setText(Price);
        if(quantity>0)
        {jchkboxSprite.setSelected(true);}
    }//GEN-LAST:event_jtxtfieldSpriteFocusLost

    private void jtxtfieldSmallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtfieldSmallActionPerformed
          
    }//GEN-LAST:event_jtxtfieldSmallActionPerformed

    private void jtxtfieldSmallFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtfieldSmallFocusGained
           if(jchkboxSpizza.isSelected())
           {
               jchkboxSpizza.setSelected(false);
           }
           jtxtfieldSmallP.setText(null);
           
    }//GEN-LAST:event_jtxtfieldSmallFocusGained

    private void jtxtfieldMediumFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtfieldMediumFocusGained
        if(jchkboxMpizza.isSelected())
           {
               jchkboxMpizza.setSelected(false);
           }
           jtxtfieldMediumP.setText(null);
    }//GEN-LAST:event_jtxtfieldMediumFocusGained

    private void jtxtfieldLargeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtfieldLargeFocusGained
        if(jchkboxLpizza.isSelected())
           {
               jchkboxLpizza.setSelected(false);
           }
           jtxtfieldLargeP.setText(null);
    }//GEN-LAST:event_jtxtfieldLargeFocusGained

    private void jtxtfieldCocaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtfieldCocaFocusGained
        if(jchkboxCoca.isSelected())
           {
               jchkboxCoca.setSelected(false);
           }
           jtxtfieldCocaP.setText(null);
    }//GEN-LAST:event_jtxtfieldCocaFocusGained

    private void jtxtfieldThumsFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtfieldThumsFocusGained
        if(jchkboxThums.isSelected())
           {
               jchkboxThums.setSelected(false);
           }
           jtxtfieldThumsP.setText(null);
    }//GEN-LAST:event_jtxtfieldThumsFocusGained

    private void jtxtfieldSpriteFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtfieldSpriteFocusGained
        if(jchkboxSprite.isSelected())
           {
               jchkboxSprite.setSelected(false);
           }
           jtxtfieldSpriteP.setText(null);
    }//GEN-LAST:event_jtxtfieldSpriteFocusGained

    private void jbtnTotalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnTotalMouseClicked
        double price1 =Double.parseDouble(jtxtfieldSmallP.getText());
        double price2 =Double.parseDouble(jtxtfieldMediumP.getText());
        double price3 =Double.parseDouble(jtxtfieldLargeP.getText());
        double price4 =Double.parseDouble(jtxtfieldCocaP.getText());
        double price5 =Double.parseDouble(jtxtfieldThumsP.getText());
        double price6 =Double.parseDouble(jtxtfieldSpriteP.getText());
        double price=price1+price2+price3+price4+price5+price6;
        String Price=String.format("%.2f", price);
        jtxtfieldSub.setText(Price);
        double tax=(price1+price2+price3+price4+price5+price6)*18/100;
        String Tax=String.format("%.2f", tax);
        jtxtfieldTax.setText(Tax);
        double total=price+tax;
        String Total=String.format("%.2f", total);
        jtxtfieldTotal.setText(Total);
        if(jtxtfieldSmall.getText()==null)
        {
            double tmp=0;
            String Tmp=String.format("%.2f", tmp);
            jtxtfieldSmall.setText(Tmp);
            jtxtfieldSmallP.setText(Tmp);
        }
        if(jtxtfieldMediumP.getText()==null)
        {
            double tmp=0;
            String Tmp=String.format("%.2f", tmp);
            jtxtfieldMediumP.setText(Tmp);
        }
        if(jtxtfieldLargeP.getText()==null)
        {
            double tmp=0;
            String Tmp=String.format("%.2f", tmp);
            jtxtfieldLargeP.setText(Tmp);
        }
        if(jtxtfieldCocaP.getText()==null)
        {
            double tmp=0;
            String Tmp=String.format("%.2f", tmp);
            jtxtfieldCocaP.setText(Tmp);
        }
        if(jtxtfieldThumsP.getText()==null)
        {
            double tmp=0;
            String Tmp=String.format("%.2f", tmp);
            jtxtfieldThumsP.setText(Tmp);
        }
        if(jtxtfieldSpriteP.getText()==null)
        {
            double tmp=0;
            String Tmp=String.format("%.2f", tmp);
            jtxtfieldSpriteP.setText(Tmp);
        }
    }//GEN-LAST:event_jbtnTotalMouseClicked

    private void jtxtfieldMediumKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtfieldMediumKeyPressed
        String EnterNumber=jtxtfieldMedium.getText();
        double quantity=Double.parseDouble(EnterNumber);
        double price=quantity*MediumPizza;
        String Price=String.format("%.2f", price);
        jtxtfieldMediumP.setText(Price);
        jchkboxMpizza.setSelected(true);
    }//GEN-LAST:event_jtxtfieldMediumKeyPressed

    private void jtxtfieldLargeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtfieldLargeKeyPressed
        String EnterNumber=jtxtfieldLarge.getText();
        double quantity=Double.parseDouble(EnterNumber);
        double price=quantity*LargePizza;
        String Price=String.format("%.2f", price);
        jtxtfieldLargeP.setText(Price);
        jchkboxLpizza.setSelected(true);
    }//GEN-LAST:event_jtxtfieldLargeKeyPressed

    private void jtxtfieldCocaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtfieldCocaKeyPressed
        String EnterNumber=jtxtfieldCoca.getText();
        double quantity=Double.parseDouble(EnterNumber);
        double price=quantity*CocaCola;
        String Price=String.format("%.2f", price);
        jtxtfieldCocaP.setText(Price);
        jchkboxCoca.setSelected(true);
    }//GEN-LAST:event_jtxtfieldCocaKeyPressed

    private void jtxtfieldThumsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtfieldThumsKeyPressed
        String EnterNumber=jtxtfieldThums.getText();
        double quantity=Double.parseDouble(EnterNumber);
        double price=quantity*ThumsUp;
        String Price=String.format("%.2f", price);
        jtxtfieldThumsP.setText(Price);
        jchkboxThums.setSelected(true);
    }//GEN-LAST:event_jtxtfieldThumsKeyPressed

    private void jtxtfieldSpriteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtfieldSpriteKeyPressed
        String EnterNumber=jtxtfieldSprite.getText();
        double quantity=Double.parseDouble(EnterNumber);
        double price=quantity*Sprite;
        String Price=String.format("%.2f", price);
        jtxtfieldSpriteP.setText(Price);
        jchkboxSprite.setSelected(true);
    }//GEN-LAST:event_jtxtfieldSpriteKeyPressed

    private void jbtnReceiptMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnReceiptMouseClicked
        String msg=("\tReceipt\n\nSmall Pizza : "+jtxtfieldSmall.getText()+"\nMedium Pizza : "+jtxtfieldMedium.getText()+"\nLarge Pizza : "
                  +jtxtfieldLarge.getText()+"\nCoca Cola : "+jtxtfieldCoca.getText()+"\nThumsUp : "+jtxtfieldThums.getText()+"\nSprite : "
                +jtxtfieldSprite.getText()+"\n\n\nTotal Amount : "+jtxtfieldTotal.getText()+" Rs."+"\n\nThank you for order to us");
        jtxtfieldReceipt.setText(msg);
    }//GEN-LAST:event_jbtnReceiptMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FoodOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FoodOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FoodOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FoodOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FoodOrder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton jbtnExit;
    private javax.swing.JButton jbtnOrder;
    private javax.swing.JButton jbtnReceipt;
    private javax.swing.JButton jbtnReset;
    private javax.swing.JButton jbtnTotal;
    private javax.swing.JCheckBox jchkboxCoca;
    private javax.swing.JCheckBox jchkboxLpizza;
    private javax.swing.JCheckBox jchkboxMpizza;
    private javax.swing.JCheckBox jchkboxSpizza;
    private javax.swing.JCheckBox jchkboxSprite;
    private javax.swing.JCheckBox jchkboxThums;
    private javax.swing.JLabel jlableSub;
    private javax.swing.JLabel jlableSub1;
    private javax.swing.JLabel jlableSub2;
    private javax.swing.JTextField jtxtfieldCoca;
    private javax.swing.JTextField jtxtfieldCocaP;
    private javax.swing.JTextField jtxtfieldDrink;
    private javax.swing.JTextField jtxtfieldLarge;
    private javax.swing.JTextField jtxtfieldLargeP;
    private javax.swing.JTextField jtxtfieldMeal;
    private javax.swing.JTextField jtxtfieldMedium;
    private javax.swing.JTextField jtxtfieldMediumP;
    private javax.swing.JTextArea jtxtfieldReceipt;
    private javax.swing.JTextField jtxtfieldSmall;
    private javax.swing.JTextField jtxtfieldSmallP;
    private javax.swing.JTextField jtxtfieldSprite;
    private javax.swing.JTextField jtxtfieldSpriteP;
    private javax.swing.JTextField jtxtfieldStatus;
    private javax.swing.JTextField jtxtfieldSub;
    private javax.swing.JTextField jtxtfieldTax;
    private javax.swing.JTextField jtxtfieldThums;
    private javax.swing.JTextField jtxtfieldThumsP;
    private javax.swing.JTextField jtxtfieldTotal;
    // End of variables declaration//GEN-END:variables
}
